import "./js/starter-modal";
import "./js/header"
import "./js/leap-year"
import "./js/computer-number";
import "./js/footer-modal";
import "./js/rps";
import "./js/calculator";
import "./js/slider";
import "./js/dino";
import "./js/time-calculator";
import "./js/soccer";
import "./js/biggest-number";
import "./js/scientists";