import "./js/leap-year";
import "./js/calculator";
import "./js/leap-year"
import "./js/computer-number";
import "./js/footer-modal";
import "./js/rps"
import "./js/calculator";
import "./js/slider.js";
import "./js/dino"
import "./js/biggest-number";